ALTER TABLE "solicitudesMatriculacion"
ADD COLUMN IF NOT EXISTS codigo VARCHAR(255),
ADD COLUMN IF NOT EXISTS apellidos VARCHAR(255),
ADD COLUMN IF NOT EXISTS nombres VARCHAR(255),
ADD COLUMN IF NOT EXISTS cedula_estudiante VARCHAR(255),
ADD COLUMN IF NOT EXISTS provincia_nacimiento VARCHAR(255),
ADD COLUMN IF NOT EXISTS canton VARCHAR(255),
ADD COLUMN IF NOT EXISTS genero VARCHAR(255),
ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE,
ADD COLUMN IF NOT EXISTS nacionalidad VARCHAR(255),
ADD COLUMN IF NOT EXISTS institucion_procede VARCHAR(255),
ADD COLUMN IF NOT EXISTS provincia_vivienda VARCHAR(255),
ADD COLUMN IF NOT EXISTS ciudad VARCHAR(255),
ADD COLUMN IF NOT EXISTS parroquia VARCHAR(255),
ADD COLUMN IF NOT EXISTS direccion VARCHAR(255),
ADD COLUMN IF NOT EXISTS telefono_convencional VARCHAR(255),
ADD COLUMN IF NOT EXISTS sector VARCHAR(255),
ADD COLUMN IF NOT EXISTS emergencia_nombres VARCHAR(255),
ADD COLUMN IF NOT EXISTS emergencia_parentesco VARCHAR(255),
ADD COLUMN IF NOT EXISTS telefono_emergencia VARCHAR(255),
ADD COLUMN IF NOT EXISTS padre_nombres VARCHAR(255),
ADD COLUMN IF NOT EXISTS padre_cedula VARCHAR(255),
ADD COLUMN IF NOT EXISTS padre_telefono VARCHAR(255),
ADD COLUMN IF NOT EXISTS padre_celular VARCHAR(255),
ADD COLUMN IF NOT EXISTS padre_profesion VARCHAR(255),
ADD COLUMN IF NOT EXISTS padre_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS direccion_trabajo_padre VARCHAR(255),
ADD COLUMN IF NOT EXISTS madre_nombres VARCHAR(255),
ADD COLUMN IF NOT EXISTS madre_cedula VARCHAR(255),
ADD COLUMN IF NOT EXISTS madre_telefono VARCHAR(255),
ADD COLUMN IF NOT EXISTS madre_celular VARCHAR(255),
ADD COLUMN IF NOT EXISTS madre_profesion VARCHAR(255),
ADD COLUMN IF NOT EXISTS madre_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS direccion_trabajo_madre VARCHAR(255),
ADD COLUMN IF NOT EXISTS representante_nombres VARCHAR(255),
ADD COLUMN IF NOT EXISTS representante_cedula VARCHAR(255),
ADD COLUMN IF NOT EXISTS representante_telefono VARCHAR(255),
ADD COLUMN IF NOT EXISTS representante_celular VARCHAR(255),
ADD COLUMN IF NOT EXISTS representante_profesion VARCHAR(255),
ADD COLUMN IF NOT EXISTS representante_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS direccion_trabajo_representante VARCHAR(255),
ADD COLUMN IF NOT EXISTS latitud VARCHAR(255),
ADD COLUMN IF NOT EXISTS longitud VARCHAR(255),
ADD COLUMN IF NOT EXISTS vive_con_estudiante_padre BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS es_representante_padre BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS vive_con_estudiante_madre BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS es_representante_madre BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS vive_con_estudiante_representante BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS es_representante_representante BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS nacionalidad_padre VARCHAR(50),
ADD COLUMN IF NOT EXISTS nacionalidad_madre VARCHAR(50),
ADD COLUMN IF NOT EXISTS nacionalidad_representante VARCHAR(50),
ADD COLUMN IF NOT EXISTS verificado BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS especialidad VARCHAR(50);

CREATE TABLE IF NOT EXISTS "Estudiante" (
    id_estudiante SERIAL PRIMARY KEY,
    apellidos VARCHAR(255) NOT NULL,
    nombres VARCHAR(255) NOT NULL,
    etnia VARCHAR(100),
    fecha_nacimiento DATE,
    calle_principal VARCHAR(255),
    calle_secundaria VARCHAR(255),
    referencia VARCHAR(255),
    cedula VARCHAR(20) UNIQUE,
    nacionalidad VARCHAR(100),
    genero VARCHAR(20),
    celular VARCHAR(30),
    foto_estudiantil TEXT,
    id_representante INTEGER,
    id_curso INTEGER,
    id_paralelo INTEGER,
    id_especialidad INTEGER,
    -- Claves foráneas (ajusta los nombres de las tablas referenciadas según tu modelo)
    FOREIGN KEY (id_representante) REFERENCES Representante(id_representante),
    FOREIGN KEY (id_curso) REFERENCES Curso(id_curso),
    FOREIGN KEY (id_paralelo) REFERENCES Paralelo(id_paralelo),
    FOREIGN KEY (id_especialidad) REFERENCES Especialidad(id_especialidad)
);
